RedisExchangeAPI.Web/RedisExchangeAPI.Web/Controllers/RedisHashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Web.Models;
using RedisExchangeAPI.Web.Service;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisExchangeAPI.Web.Controllers
{
    public class RedisHashTypeController : BaseController
    {
       
        private string listkey = "hashKey";

        public RedisHashTypeController(RedisService redisService) : base(redisService)
        {
           
        }

        public IActionResult Index()
        {
            Dictionary<string,string> namesList = new Dictionary<string, string>();
            if (db.KeyExists(listkey))
            {
                db.HashGetAll(listkey).ToList().ForEach(x => { namesList.Add(x.Name.ToString(),x.Value); });
            }
            return View(namesList);
        }

        [HttpPost]
        public IActionResult Add(string key , string value)
        {
            db.HashSet(listkey, key, value);
            return RedirectToAction("Index");

        }


        public IActionResult Remove(string name)
        {
            db.HashDelete(listkey, name);
            return RedirectToAction("Index");

        }
    }
}

RedisExchangeAPI.Web/RedisExchangeAPI.Web/Views/RedisHashType/Index.cshtml
@model Dictionary<string, string>
@{
}


<h2> Hash Kullanımı </h2>

<form asp-controller="RedisHashType" asp-action="Add" method="post">
    <input type="text" placeholder="key" name="key" />
    <input type="text" placeholder="value" name="Value" />
    <button type="submit" name="btnSave">Ekle</button>
</form>
<br />

<h1>Listeleme</h1>

@foreach (var item in Model)
{
    <h2>Name : @item.Key -> @item.Value   <a asp-action="Remove" asp-controller="RedisHashType" asp-route-name="@item.Key">Sil</a> </h2>
    <br />
}