RedisExchangeAPI.Web/RedisExchangeAPI.Web/Controllers/RedisListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Web.Models;
using RedisExchangeAPI.Web.Service;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedisExchangeAPI.Web.Controllers
{
    public class RedisListTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase db;
        public RedisListTypeController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.GetDb(1);
        }
        public IActionResult Index()
        {
            List<string> lstNames = new List<string>();
            if (db.KeyExists("names"))
            {
                db.ListRange("names").ToList().ForEach(x=> { lstNames.Add(x.ToString()); });

            }
            return View(lstNames);
        }



       
        public IActionResult Add(string Name)
        {
            db.ListRightPush("names", Name); //tek tek ekler
          return  RedirectToAction("Index");
        }

        public IActionResult Remove(string Name)
        {
            db.ListRemove("names",Name);
            return RedirectToAction("Index");
        }

    }
}

RedisExchangeAPI.Web/RedisExchangeAPI.Web/Views/RedisListType/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model List<string>
@{
}

<h2>Personel Kayıt İşlemi</h2>
<form method="post" action="@Url.Action("Add", "RedisListType")">

    <input type="text" name="Name" />
    <button type="submit" name="btnSave">Ekle</button>
</form>
<br />
<h2>Personel Silme İşlemi</h2>
@*<form method="post" action="@Url.Action("Remove", "RedisListType")">

    <input type="text" name="Name" />
    <button type="submit" name="btnSave">Sil</button>
</form>*@



<form asp-controller="RedisListType" asp-action="Remove" method="post">

    <input type="text" name="Name" />
    <button type="submit" name="btnSave">Sil</button>
</form>

<br />

@foreach (string item in Model)
{
    <h3>@item</h3>
    <br />
}